name: build
on:
  push:
    branches:
      - main
    tags-ignore:
      - '*.*'
  pull_request:
    branches:
      - main

jobs:
 test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version file: go.mod

    - name: Install Task
      uses: arduino/setup-task@v2

    - name: Test
      run: |
        task test